### PR TITLE
Improve notes for installing, and Makefile fur testing.

### PR DESCRIPTION
**Pull request by jfdm**
When getting blodwen to install on my machine, I encountered hidden state and assumptions.

1. Chez scheme is not called `scheme` or `chez` on all platforms.
2. Let's give details on where to find more information about Blodwen's dependencies.
3. Chicken requires numbers.
4. Testing requires an installed blodwen.

Cherry pick as you see fit on this.

### CODE REVIEW

**Comment by edwinb** [comment]
I don't think test should depend on install - does your edit to the BLODWEN_PATH in the Makefile not fix this?

**Comment by jfdm** [comment]
urgh, i thought i removed the dependancy when I included the proper change! Will fix now, and push. Sorry about that.

**Comment by jfdm** [comment]
Fixed now, I rewrote the history and rebased on master. Sorry about the confusion.

**Comment by LeifW** [comment]
Was there a recommended way to account for different names of the scheme executables?
On Arch Linux and OpenBSD at least, `csc` and `csi` are `chicken-csc` and `chicken-csi` (so as not to conflict with the executables provided by Mono - think C#):
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/chicken#n29

**Comment by christian-public** [comment]
@LeifW Are you looking for Idris 2 (https://github.com/edwinb/Idris2)? The Idris 2 repo has replaced the Blodwen repo. Idris 2 also includes a solution to your problem:

Idris 2's Chicken code generator allows the executables to be overridden by environment variables (See: https://github.com/edwinb/Idris2/blob/master/src/Compiler/Scheme/Chicken.idr#L23-L31)

The Chicken code generator could also look for multiple executables, similar to what the Chez code generator does (See: https://github.com/edwinb/Idris2/blob/952abe7fc86f62f05763d4a10fe8a999ead26b72/src/Compiler/Scheme/Chez.idr#L22-L29).

**Comment by LeifW** [comment]
Thanks! chicken-csc is the name of the chicken compiler on at least a couple platforms. So it's a common-ish name, but given that it was chosen to not conflict with the `csc` command from Mono, I don't think I'd want it to look for multiple executables and use the first one it finds, in case they have the C# compiler installed.
I was interested in making a package of Idris2, and e.g. on Arch I think I'd like to be able to set the name of the chicken compiler via e.g. a `./configure` argument, so that it's built into  the executable - that way the end user of the package wouldn't need to set an environment variable for something that's already a given based on their OS. I know Idris1 had the path to the Idris libraries hardcoded into the executable via the `configure` command of Cabal.

**Pull request merged**
